---
- name: My Test Playbook
  hosts: webservers
  become: true
  tasks:
  - name: Install Httpd
    yum:
      name: httpd
      state: present

  - name: Start Httpd
    service:
      name: httpd
      state: started
