---
- name: Installing Httpd
  yum:
    name: httpd
    state: present
  when: ansible_os_family == "RedHat"
  notify: start httpd

- name: Installing Apache2
  apt:
    name: apache2
    state: present
  when: ansible_os_family == "Debian"
  notify: start apache2

- name: Copy index.html
  copy:
    src: /home/ansadmin/index.html
    dest: /var/www/html
    mode: 0666
